//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqlite.CodeCreate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sqlite.CodeCreate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from [{0}] limit 0.
        /// </summary>
        internal static string qry_Fields {
            get {
                return ResourceManager.GetString("qry_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    m.name
        ///    , p.*
        ///FROM
        ///    sqlite_master m
        ///    JOIN pragma_foreign_key_list(m.name) p ON m.name != p.&quot;table&quot;
        ///WHERE m.type = &apos;table&apos;
        ///ORDER BY m.name
        ///;.
        /// </summary>
        internal static string qry_ForeignKeys {
            get {
                return ResourceManager.GetString("qry_ForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  m.name AS table_name, 
        ///  p.cid AS col_id,
        ///  p.name AS col_name,
        ///  p.type AS col_type,
        ///  p.pk AS col_is_pk,
        ///  p.dflt_value AS col_default_val,
        ///  p.[notnull] AS col_is_not_null
        ///FROM sqlite_master m
        ///LEFT OUTER JOIN pragma_table_info((m.name)) p
        ///  ON m.name &lt;&gt; p.name
        ///WHERE m.type = &apos;table&apos;
        ///ORDER BY table_name, col_id.
        /// </summary>
        internal static string qry_MetaData {
            get {
                return ResourceManager.GetString("qry_MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from sqlite_master where [type] = &apos;table&apos; and name not like &apos;sqlite_%&apos;.
        /// </summary>
        internal static string qry_Tables {
            get {
                return ResourceManager.GetString("qry_Tables", resourceCulture);
            }
        }
    }
}
